# Site settings
title: Deerfox Digital
email: contact@deerfox.dev
baseUrl: ""
url: https://deerfox.dev
description: >-
  Deerfox Digital provides game and software development services. We specialize in Unity, Unreal Engine, and React Native.
keywords: "web development, game programming, mobile apps"
skills: "Web Development • Game Programming • Mobile Apps"
#meta_author: LastName FirstName

## Google webmaster tools
#google_verify:
#
## https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
#bing_verify:

# Contact form:
# - static : pass through formspree.io to validate email sending
# - disqus : replace contact form by disqus thread
# - comment the line below if you want to stick with the default PHP contact form
contact: static

# Color settings (hex-codes without the leading hash-tag)
color:
#  primary: 18bc9c # light green cerulean
#  primary-rgb: "24,288,156" # light green cerulean
#  secondary: 2c3e50 # header, light navy
#  secondary-dark: 233140 # footer, navy
  primary: 588157 # grass
  primary-rgb: "88,129,87" # grass
  secondary: 3a5a40 # dark, header
  secondary-dark: 344e41 # darkest, footer

# Footer settings
footer:
  copyright: Dr. Henry Jekyll
  location: Location
  social: Around the Web
  credits: Credits

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/jekyllrb
  - title: facebook
    url:
  - title: stack-overflow
    url: http://stackoverflow.com/questions/tagged/jekyll
  - title: bitbucket
    url: http://bitbucket.org/jekyll
  - title: github
    url: http://github.com/jekyll

# Postal address (add as many lines as necessary)
address:
  - line: Calgary, AB
  - line: Canada

# Credits content
credits: 'Deerfox Digital provides game and software development services. We specialize in Unity, Unreal Engine, React, and React Native. Calgary-based, Canada-wide. If you have a project in mind, we would love to hear from you!'

# Build settings
markdown: kramdown
permalink: pretty

#for posts
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      permalink: ""
